[package]
name = "explr-merge-base"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
custom_logger = { git = "https://github.com/winksaville/custom_logger", version = "0.3.0" }
log = "0.4.22"
